paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title.html

url: https://www.jsxc.org/

gems:
  - jekyll-feed
  - jekyll-paginate
  - octopress-autoprefixer

markdown: redcarpet

include: ["vendor"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
